# this python script uses python files generated by protobuf

# to install on windows, go to https://github.com/protocolbuffers/protobuf/releases and download for your architecture

# you can add it to your PATH using for example : 

# [Environment]::SetEnvironmentVariable('Path', $env:Path + ";C:\Users\{your user}\Downloads\protoc-24.4-win64\bin", [EnvironmentVariableTarget]::User)

# then, you can generate python files using

# protoc -I=protobuf/ --python_out=protobuf protobuf/telemetry.proto

import socket
import telemetry_pb2 as telemetry_pb2

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(("192.168.42.2", 5005))
sock.setblocking(0)

while True:
    try:
        data, addr = sock.recvfrom(1024)  # Buffer size de 1024 octets
        telemetry_data = telemetry_pb2.VitiroverTelemetry()
        telemetry_data.ParseFromString(data)

        # Afficher quelques valeurs
        print(f"Robot ID: {telemetry_data.robot_id}")
        print(f"Error GNSS (cm): {telemetry_data.error_gnss_cm}")
        print(f"Heading: {telemetry_data.heading}")
        print(f"Battery Voltage: {telemetry_data.battery_voltage}")

    except BlockingIOError:
        # Pas de données reçues
        pass
    



